version: '3'

services:
  app_dev:
    container_name: app_dev
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: app_dev
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
  app_prod:
    container_name: app_prod
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: app_prod
    ports:
      - "3001:3000"      
